apiVersion: batch/v1
kind: Job
metadata:
  name: gcs-fuse-warp-test-with-buffered-read-0
spec:
  parallelism: 1
  completions: 1
  completionMode: Indexed
  template:
    metadata:
      labels:
        app: gcs-fuse-warp-test
      annotations:
        gke-gcsfuse/volumes: "true"
        gke-gcsfuse/cpu-limit: "0"
        gke-gcsfuse/memory-limit: "0"
        gke-gcsfuse/ephemeral-storage-limit: "0"
    spec:
      restartPolicy: Never
      hostNetwork: true
      serviceAccountName: warp-benchmark
      containers:
        - name: gke-gcsfuse-sidecar
          image: gcr.io/gcs-tess/princer/gcs-fuse-csi-driver-sidecar-mounter:v1.13.4-gcsfuse-2.12.1
        - name: gcs-fuse-warp-test
          image: ubuntu:latest
          command:
            - "/bin/bash"
            - "-c"
            - |
              set -e
              echo "Reading 5GiB using dd command:"
              time dd if=/mnt/disks/test-bucket/5G/experiment.0 of=/dev/null bs=1M count=5120 iflag=direct

          volumeMounts:
            - name: gcs-fuse-warp-test-volume
              mountPath: /mnt/disks/test-bucket
      volumes:
        - name: gcs-fuse-warp-test-volume
          csi:
            driver: gcsfuse.csi.storage.gke.io
            readOnly: false
            volumeAttributes:
              bucketName: "gcs-fuse-warp-test-bucket"
              mountOptions: "enable-buffered-read,read:block-size-mb:16,read:global-max-blocks:60,read:max-blocks-per-handle:30,read:start-blocks-per-handle:2,implicit-dirs,metadata-cache:ttl-secs:-1,metadata-cache:stat-cache-max-size-mb:-1,metadata-cache:type-cache-max-size-mb:-1,log-severity=trace"
