apiVersion: batch/v1
kind: Job
metadata:
  name: gcs-fuse-warp-test-with-fix
spec:
  parallelism: 1
  completions: 1
  completionMode: Indexed
  template:
    metadata:
      labels:
        app: gcs-fuse-warp-test
      annotations:
        gke-gcsfuse/volumes: "true"
        gke-gcsfuse/cpu-limit: "0"
        gke-gcsfuse/memory-limit: "0"
        gke-gcsfuse/ephemeral-storage-limit: "0"
    spec:
      restartPolicy: Never
      serviceAccountName: warp-benchmark
      containers:
        # - name: gke-gcsfuse-sidecar
        #   # image: gcr.io/gcs-tess/princer_google_com_20250717164207/gcs-fuse-csi-driver-sidecar-mounter:v1.17.0-16-gafdf413b
        #   image: gcr.io/gcs-tess/princer_google_com_20250718045802/gcs-fuse-csi-driver-sidecar-mounter:v1.17.0-16-gafdf413b
        - name: gcs-fuse-warp-test
          image: ubuntu:latest
          command:
            - "/bin/bash"
            - "-c"
            - |
              set -e

              # apt-get update
              # apt-get install -y golang curl sudo gnupg git
              # apt-get install -y python3 python3-pip
              # git clone https://github.com/GoogleCloudPlatform/gcsfuse-tools.git
              # cd gcsfuse-tools
              # git checkout princer
              # cd holrepro
              # python3 repro.py --file_path /mnt/disks/test-bucket/64M/0_file_1000000_0__0 --num_handles 1
              pwd
              ls -la
              ls /mnt/disks/test-bucket

          volumeMounts:
            - name: gcs-fuse-warp-test-volume
              mountPath: /mnt/disks/test-bucket
      volumes:
        - name: gcs-fuse-warp-test-volume
          csi:
            driver: gcsfuse.csi.storage.gke.io
            readOnly: false
            volumeAttributes:
              bucketName: "gcs-fuse-warp-test-bucket"
              # mountOptions: "enable-cloud-profiling,profiling:label:gke-test4,implicit-dirs,metadata-cache:ttl-secs:-1,metadata-cache:stat-cache-max-size-mb:-1,metadata-cache:type-cache-max-size-mb:-1,log-severity=trace"
              mountOptions: "implicit-dirs,metadata-cache:ttl-secs:-1,metadata-cache:stat-cache-max-size-mb:-1,metadata-cache:type-cache-max-size-mb:-1,log-severity=trace"
